import logging
from datetime import datetime, timezone
from urllib.parse import quote

from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.constants import (
    EMAIL_VERIFICATION_EXPIRE_MINUTES,
    PASSWORD_RESET_EXPIRE_MINUTES,
)
from app.core.exceptions import UnauthorizedError, ValidationError
from app.core.security import get_password_hash, verify_token
from app.models.token import TokenType
from app.models.user import UserStatus
from app.schemas.user import PasswordResetConfirm, PasswordResetRequest, TokenResponse, UserLogin
from app.services.email_service import send_email, send_password_reset
from app.services.user_service import UserService

logger = logging.getLogger(__name__)


def _greeting(user) -> str:
    """"Hello Ada", falling back through what the account actually has.

    The email address is the last resort rather than the first, because a mail
    that greets you by your own address reads as generated by something that
    knows nothing about you — which, on a password reset, is the impression to
    avoid.
    """
    return f"Hello {user.full_name or user.username or user.email},"


class AuthService:
    def __init__(self, db: Session):
        self.db = db
        self.user_service = UserService(db)

    def login(self, credentials: UserLogin) -> TokenResponse:
        """Login with email and password"""
        user = self.user_service.authenticate_user(credentials.email, credentials.password)
        if not user:
            raise UnauthorizedError("Invalid email or password")

        if not user.is_active:
            raise UnauthorizedError("User account is deactivated")

        if user.status == UserStatus.PENDING_VERIFICATION:
            raise UnauthorizedError("Please verify your email before logging in")

        return self._create_token_pair(user)

    # google_login() and register() were removed along with their endpoints —
    # see the note in app/api/v1/endpoints/auth.py. The admin account comes from
    # the seed script, so nothing needs a public signup path. The rest of the
    # Google scaffolding (service method, schemas, two columns) went with the
    # migration that drops google_id and google_email.

    def refresh_token(self, refresh_token: str) -> TokenResponse:
        """Exchange a refresh token for a new token pair."""
        token_data = verify_token(refresh_token, expected_type=TokenType.REFRESH.value)
        if not token_data:
            raise UnauthorizedError("Invalid refresh token")

        # The signature alone is not enough: logout() and reset_password() revoke
        # the row, not the JWT. Checking only the signature here left the other
        # half of the logout hole open — a stolen refresh token kept minting
        # fresh access tokens for its full 30 days after the user logged out.
        if not self.user_service.get_valid_token(refresh_token, TokenType.REFRESH):
            raise UnauthorizedError("Invalid refresh token")

        user_id = int(token_data["sub"])
        user = self.user_service.get_user_by_id(user_id)
        if not user or not user.is_active:
            raise UnauthorizedError("User not found or inactive")

        # Revoke old refresh token
        self.user_service.revoke_token(refresh_token)

        return self._create_token_pair(user)

    def logout(self, access_token: str, refresh_token: str = None) -> bool:
        """Logout user by revoking tokens"""
        # Revoke access token
        self.user_service.revoke_token(access_token)

        # Revoke refresh token if provided
        if refresh_token:
            self.user_service.revoke_token(refresh_token)

        return True

    def request_password_reset(self, request: PasswordResetRequest) -> None:
        """Mail a reset link, if there is an account that can use one.

        Returns None in every case, and that is the whole design. The endpoint
        answers the same 200 and the same sentence whether or not the address is
        registered, so the form cannot be used to find out which addresses exist
        — the same property /auth/login protects by answering one 401 to every
        kind of bad credential.

        Three of the four ways out below used to differ from each other:

        * unknown address — returned quietly, which was right;
        * an account with no password — *raised*, so a 422 came back where a
          200 would have. One malformed response is all an enumerator needs, and
          this one said "this address is registered" out loud;
        * a deactivated account — was not considered at all, and was mailed a
          working link to a door it cannot open;
        * everything else — mails the link.

        They all answer the same way now. What separates them is the log, which
        is where an operator can see the difference and an attacker cannot.
        """
        user = self.user_service.get_user_by_email(request.email)
        if not user:
            # Not the address itself: the log is the one place this flow keeps a
            # record, and a list of addresses that guessed wrong is not worth
            # collecting.
            logger.info("Password reset requested for an address with no account")
            return

        # Kept after the OAuth removal, which is what made the column nullable in
        # the first place. Every account now has a password, so this should be
        # unreachable — but a null here would otherwise reach reset_password()
        # and fail on a hash comparison against None.
        if not user.hashed_password:
            logger.warning("Password reset skipped: user id=%s has no password set", user.id)
            return

        if not user.is_active:
            logger.warning("Password reset skipped: user id=%s is deactivated", user.id)
            return

        # Any reset link already in flight stops working here.
        #
        # Without this, every request left another live key to the account
        # behind, all valid for the full hour — so the flow an attacker uses to
        # spray reset mail is also the flow that accumulates the tokens. It also
        # matches what a person expects after clicking "send it again": the
        # newest mail is the one that works.
        self.user_service.revoke_all_user_tokens(user.id, TokenType.RESET_PASSWORD)

        reset_token = self.user_service.create_token(
            user.id,
            TokenType.RESET_PASSWORD,
            expires_in_minutes=PASSWORD_RESET_EXPIRE_MINUTES,
            metadata={"purpose": "password_reset"}
        )

        self._send_password_reset_email(user, reset_token)

    def reset_password(self, request: PasswordResetConfirm) -> bool:
        """Reset password using token"""
        # Verify reset token
        token = self.user_service.get_valid_token(request.token, TokenType.RESET_PASSWORD)
        if not token:
            raise ValidationError("Invalid or expired reset token")

        payload = verify_token(request.token, expected_type=TokenType.RESET_PASSWORD.value)
        if not payload:
            raise ValidationError("Invalid or expired reset token")

        user_id = int(payload["sub"])
        user = self.user_service.get_user_by_id(user_id)
        if not user:
            raise ValidationError("User not found")

        # A link minted before the account was deactivated must not be a way
        # back in. Worded the same as an expired token, deliberately: the person
        # holding the link is not necessarily the account holder.
        if not user.is_active:
            raise ValidationError("Invalid or expired reset token")

        # Update password
        user.hashed_password = get_password_hash(request.new_password)
        user.updated_at = datetime.now(timezone.utc)
        self.db.commit()
        
        # Revoke all user tokens
        self.user_service.revoke_all_user_tokens(user.id)
        
        return True

    def verify_email(self, token: str) -> bool:
        """Verify email using verification token"""
        # Verify email verification token
        token_obj = self.user_service.get_valid_token(token, TokenType.EMAIL_VERIFICATION)
        if not token_obj:
            raise ValidationError("Invalid or expired verification token")

        payload = verify_token(token, expected_type=TokenType.EMAIL_VERIFICATION.value)
        if not payload:
            raise ValidationError("Invalid or expired verification token")

        user_id = int(payload["sub"])
        user = self.user_service.get_user_by_id(user_id)
        if not user:
            raise ValidationError("User not found")
        
        # Mark email as verified
        user.is_verified = True
        user.status = UserStatus.ACTIVE
        user.email_verified_at = datetime.now(timezone.utc)
        self.db.commit()
        
        # Revoke verification token
        self.user_service.revoke_token(token)
        
        return True

    def resend_verification_email(self, email: str) -> bool:
        """Resend email verification.

        Returns quietly for unknown or already-verified addresses. It used to
        raise "User not found", which let anyone enumerate registered emails —
        request_password_reset() one method up already got this right.
        """
        user = self.user_service.get_user_by_email(email)
        if not user or user.is_verified:
            return True

        # Create new verification token
        verification_token = self.user_service.create_token(
            user.id,
            TokenType.EMAIL_VERIFICATION,
            expires_in_minutes=EMAIL_VERIFICATION_EXPIRE_MINUTES,
            metadata={"purpose": "email_verification"}
        )

        # Send verification email
        self._send_verification_email(user, verification_token)

        return True

    def _create_token_pair(self, user) -> TokenResponse:
        """Create access and refresh token pair.

        Lifetimes come from settings rather than being hardcoded here — they
        used to say 30 minutes and 7 days while the config said something else
        entirely, so the documented values were never the ones in effect.
        """
        access_minutes = settings.ACCESS_TOKEN_EXPIRE_MINUTES
        refresh_minutes = settings.REFRESH_TOKEN_EXPIRE_DAYS * 24 * 60

        access_token = self.user_service.create_token(
            user.id,
            TokenType.ACCESS,
            expires_in_minutes=access_minutes
        )

        refresh_token = self.user_service.create_token(
            user.id,
            TokenType.REFRESH,
            expires_in_minutes=refresh_minutes
        )

        return TokenResponse(
            access_token=access_token,
            refresh_token=refresh_token,
            token_type="bearer",
            expires_in=access_minutes * 60,
            user_id=user.id,
            email=user.email
        )

    def _send_verification_email(self, user, token: str = None) -> None:
        """Send email verification"""
        if not token:
            token = self.user_service.create_token(
                user.id,
                TokenType.EMAIL_VERIFICATION,
                expires_in_minutes=EMAIL_VERIFICATION_EXPIRE_MINUTES,
                metadata={"purpose": "email_verification"}
            )
        
        link = f"{settings.frontend_base_url}/verify-email?token={quote(token, safe='')}"
        subject = "Verify Your Email Address"
        body = (
            f"{_greeting(user)}\n\n"
            f"Please verify your email address by opening this link:\n\n"
            f"{link}\n\n"
            f"The link expires in {EMAIL_VERIFICATION_EXPIRE_MINUTES // 60} hour.\n\n"
            f"If you didn't create an account, ignore this email.\n"
        )

        self._send_email(user.email, subject, body)

    def _send_password_reset_email(self, user, token: str) -> None:
        """Send the reset link.

        The token is percent-encoded into the query string rather than
        interpolated raw. A JWT is base64url plus dots and needs no escaping
        today — but "needs no escaping today" is how a `+` in a token ends up
        read as a space by the page on the other end, and the failure looks
        exactly like an expired link.
        """
        if not settings.emails_enabled:
            # The normal state in CI and on a fresh clone. Warning rather than
            # debug, unlike the contact notification: a contact mail nobody
            # configured is a feature left off, but a reset link that cannot be
            # delivered is someone locked out of their own account with the API
            # cheerfully answering 200. The token itself is deliberately not
            # logged — a log line is not a private channel, and this one would
            # be a live key to the account.
            logger.warning(
                "SMTP is not configured; password reset link for user id=%s was not sent",
                user.id,
            )
            return

        link = f"{settings.frontend_base_url}/reset-password?token={quote(token, safe='')}"

        # Best-effort for the same reason _send_email is: a mail outage must not
        # turn this into a 500, because a 500 here is the enumeration signal that
        # request_password_reset() spends four branches avoiding.
        try:
            send_password_reset(
                user.email,
                greeting=_greeting(user),
                reset_url=link,
                expires_minutes=PASSWORD_RESET_EXPIRE_MINUTES,
            )
        except Exception:
            logger.exception("Failed to send password reset email to user id=%s", user.id)
        else:
            logger.info("Password reset email sent to user id=%s", user.id)

    def _send_email(self, to_email: str, subject: str, body: str) -> None:
        """Send mail, best-effort.

        The transport moved to ``email_service.send_email``, which raises; these
        flows keep swallowing, as they did before, so that a password-reset
        request does not 500 on a mail outage. What changed is that the failure
        now reaches the logger instead of stdout, where nothing was collecting it.

        The ``emails_enabled`` check is what .env.example has always claimed
        happens — "leave SMTP_USER/SMTP_PASSWORD blank and nothing is sent" was
        true of the contact notification and not of this path, which went on to
        open a socket and log a traceback on every run of the test suite.
        """
        if not settings.emails_enabled:
            logger.debug("Email to %s skipped: SMTP is not configured", to_email)
            return

        try:
            send_email(to_email, subject, body)
        except Exception:
            logger.exception("Failed to send email to %s", to_email)
